sudo: false
language: node_js
node_js:
  - "4"
addons:
  apt:
    packages:
      - sshpass
      - graphicsmagick
  ssh_known_hosts: karl-jaspers.com
env:
  global:
    - secure: "WQ8dIm03EPa5VcGmKD4yw3I7QKV7BNVvxz6kfU5P2y5c0sQZhlgM62LnpHaAx8Ru7Xglq1BG+PBja8h1fSKRJCr7kU85e4Eq1O2nZs1PPPDhvm5x4KuFtTbuhjHP2c27M5MS/Y+ssT0nyBN3HFfgTSVsPN0CGwi4+RUQloOauzXE7FoDCthiaaRhjtH12E7NLy7yeMbqLxgHqIYVvjPyhOCoAq2wXhY0Q1TAqYL9xVxzNDjZCLBu4Z630Ul83pZXZsZ1Fe8zFtCl9MpbMi3lMacTYKIWD0gDMEmyRSmBM0sScnrsZRkFckk4/Qb6tSqJvmmY6CSUGshpAQMZgispiDVvIvFwaL4lLGyxX9Wl3ytjwhMIL9gDwNdorHl5zu/NP/9FMzY/BvP7fjL9VLxz5iZeSwGOTDAOcp+CznezaZus+6I19u0sckqtwQI0l6Hyvq8FOJ2IUcr+z0bYu07u/en9rRNnwm4PgEFOCVByHe0zfJf65LFaUUAH0tXAPt7yUmCAgsvfTRn4GCaj3k1o6CuoYtvYo2KlkIm9qx+MejLXmZ2wAzDj6AHOApo5nTT0qfKUAY3OoUM9GmzyZv1QGplQjL9JmyD4E7uoFNGm42Z8Eg/wq97VfPoZ/73eeY6s9eblzs9DI5/L45/IpLMiONA6Z4b85m/QfukiurVREBQ="
    - secure: "B2ea8G+3XnMRKOMKtk/uCMYvKrreibSxPd7kjxuSC4YqlJcpZ3NXkl8zq2729dC1eAlq+GL4qXI0BJyD0dBQfWGNK9bbPnOF1ieQu2Ejr382Rz8ddgmkyYLxvVTqw0v7ATiVLd4rKVUtg7degzFYrhks50znB2cuBlL6aNAoi5q8itwdVXk8CLzeNQhIg1ncuCOxXfeSUGrwBx9Ta8p04M3SJV1ZAyPV9BywBIzefiUz0Gb0GX9nsoFiL2d7lkqLliM+oQhW2djzU67hcMW+F/5RVMRA2i+RmtXLe+wtIOwWqJ/6yJBmIAb+sm4j5D+qRuDr462bvUfAoZxLBJwcVuvQgDH8hDZwd7Hr07txVycTFJAMkKYQw4+p0mha61K8NwPvSwJkNFYYk+X25asGXeYSW3Fac4bSiD1v/M0crMIuUNBOZzBgti+iDOF3a8zg7f3mqzA5tb3UnK+pEwMAWMKStI4L/OHbiplo2lRiRB2DgFMEvz70URjVzuO5qHGv4EnYmEiJQGeqKanrYE1a4rQCx4DE9caVNlJvDpZ2ajh1VxnpbFiYI++XbrF4yRDj6OnbR3zfeSZ9naeXComt2MVzd3NQtZd1lCqYUGLda0gF6OuVBiNR7B7hyp1vo/y3NzGDYfo47Ii1aA30PH5ylkB+BXfnIx9iEIhR910aBFE="
script:
  - npm run gulp
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
